### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by chrisvte** [tamland/airsonic-frontend#1]
I have airsonic running in Ubuntu 18.04 and I want to use this frontend but I don't know how to do it.

I downloaded the code from git and tried the command "yarn install" but the only I got was:

"00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'"

First time using yarn, so I am kind of lost.

**Comment by SteveDinn** [comment]
When it was posted about on Reddit, I commented with a simple DockerFile. You could run it in a container if you wanted.
https://www.reddit.com/r/airsonic/comments/i4o8g9/modern_responsive_frontend_beta/g0kxx7a/

**Comment by SteveDinn** [comment]
```
FROM node:14.7.0-alpine3.12

WORKDIR /usr/src/app

COPY ./package.json .
RUN yarn install

ADD . /usr/src/app

RUN yarn build

# Start
CMD [ "yarn", "serve" ]
EXPOSE 8080
```

**Comment by SteveDinn** [comment]
Just noticed that @tamland posted an official docker image. Scratch my comment, and use that.

**Comment by chrisvte** [comment]
I didn't want to use docker but I really appreciate your help.
At the end it was something related with my yarn version outdated. So, here is the steps I took to solve it:

$ apt remove cmdtest yarn
$ npm install -g yarn
$ npm cache clean -f 
$ npm install -g n 
$ n stable

Relogin.

$ cd /opt/
$ wget https://github.com/tamland/airsonic-frontend/archive/master
$ unzip master.zip
$ cd airsonic-frontend-master/
$ yarn install
$ yarn serve

Open http://server-ip:8081

Now that it is working I having issues knowing what to put under "Server" field to login. I think is some kind of URL with the "/api" at the end, but I don't know.

**Comment by chrisvte** [comment]
u_u 
It was really easy the last problem, it was just my server URL like http://server-ip:8080/airsonic, nothing to do with "/api", "/rest"...
So, time to try this front end.
Thanks!

**Comment by gimzmoe** [comment]
I know you resolved it but I get to the point
For the server I tried 
http://server-ip:8080/airsonic
http://localhost:8080/airsonic
http://server-ip:8080/
http://localhost:8080/
all give me "Could not log in. (Network Error)"
