### ISSUE TITLE
[Feature Request] Have the ability to configure the airsonic server in advance

### ISSUE THREAD

**Issue by SteveDinn** [tamland/airsonic-frontend#11]
I know I already mentioned this issue, but I thought I'd break it out into its own item for tracking.

I only plan to use this frontend with my personal Airsonic server, so I'd like to be able to configure the frontend to use that server exclusively and have it not even show the server field in the login screen, or at least have the value already populated on the login screen.

**Comment by marcoprolog** [comment]
Maybe it's because I'm not too familiar with node/yarn, but is there a way to set up the environment variable when building from source instead of using docker?

I figured out how to make the env.js file manually and it works fine, but it gets removed every time I build.
Thanks! :D
