### ISSUE TITLE
Could not log in. (Network Error) 

### ISSUE THREAD

**Issue by gimzmoe** [tamland/airsonic-frontend#17]
The inputs from issue #1 were helpful, however I'm stuck at the "login"
I'm running airsonic and airsonic-frontend on the same machine (raspberry pi 4) 
I'm not an node/npm user and the only way I understand to start the frontend server is using:

`sudo yarn serve`

For the server I tried
http://server-ip:8080/airsonic
http://localhost:8080/airsonic
http://server-ip:8080/
http://localhost:8080/
all give me "Could not log in. (Network Error)"

**Comment by gimzmoe** [comment]
http://server-ip:8080 is working today, not sure if the omission of the trailing "/" is the key...

**Comment by pwepwe973** [comment]
yes I had the same problem and removing the "/" at the end of the airsonic server address solved the problem
