### ISSUE TITLE
[Question] Running proxied behind NGINX?

### ISSUE THREAD

**Issue by SteveDinn** [tamland/airsonic-frontend#2]
I want to run this app proxied behind an NGINX reverse proxy. I feel like I'm going to have two issues:
1. Can I configure this app to run from a subfolder? i.e., http://example.com/airsonic-frontend or something similar.
2. Am I correct in assuming that the connection to the actual Airsonic server is done from the client browser, and not from the web server hosting the app? Several Airsonic Android apps provide a configuration option for a primary and secondary URL for the same Airsonic server so that it can be accessed from both inside (directly) and outside your home network (proxied). Is this sort of configuration possible? I feel like that's more of a feature request.

**Comment by tamland** [comment]
1: It's possible but requires custom build as the path need to be set compile time. If you can, I recommend using a subdomain or mapping the fronted on the root and backends on `/api` or something. Running multiple applications on the same domain can also cause issues as they will all share the same client storage.

2: That's correct. Not sure how the client can 'know' which one to use or what the purpose would be..

**Comment by SteveDinn** [comment]
Re: 2, I am thinking too much from the perspective of a mobile client whose location changes regularly, but I think that's more appropriate for an app.

**Comment by SteveDinn** [comment]
Is a user able to configure the app to start up with the airsonic URL pre-configured?

**Comment by tamland** [comment]
Not yet but I plan to add it.
