### ISSUE TITLE
[Question] How to build to support nginx proxied version

### ISSUE THREAD

**Issue by jacroe** [tamland/airsonic-frontend#28]
I'm already having to do a custom build to make the project work on ARM. So I might as well also change what's necessary to make it support being behind an nginx proxy, as mentioned in #2.

What do I need to change to make the app available at, say, http://example.com/music/ ?

**Comment by tamland** [comment]
To get the build correct it should be sufficient to change [publicPath](https://cli.vuejs.org/config/#publicpath) to `music/` (Not tested tho). Might need some additional nginx magic, I'm not sure.
