### ISSUE TITLE
[Feature Request] Last FM scrobbling

### ISSUE THREAD

**Issue by SteveDinn** [tamland/airsonic-frontend#3]
This one should be pretty straightforward. The airsonic client should call the scrobbling API after a song has been playing for some amount of time, 5 or 10 seconds should be sufficient. Just in order to not scrobble tracks as you're skipping through them. 

http://www.subsonic.org/pages/api.jsp#scrobble

**Comment by angerson** [comment]
FYI: Navidrome requires a scrobble call to record when a track is played (https://github.com/deluan/navidrome/issues/593), so without this feature, the recently- and most-frequently- features on Navidrome don't work.
