### ISSUE TITLE
[Bug] If a new user has not played anything, "Home" tab does not load properly.

### ISSUE THREAD

**Issue by SteveDinn** [tamland/airsonic-frontend#4]
I believe the "recently played" and "most played" APIs are not returning with any results, so the home page never finishes loading.

**Comment by tamland** [comment]
Thanks for reporting!

**Comment by SteveDinn** [comment]
No problem. I'm thinking of lots of feature requests as I use the app more and more. It's great!
To be honest, I haven't found many actual bugs, just things I'd also like it to do :)
